name: Nikola Tesla
favicon: null
layout_spectrum: 0.5166156119666994
typography_spectrum: 0.5594038085546345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.16858973121270537
  lightness: 0.635110019473359
  saturation: 0.9231484262272716
  rhythmicContrast: 0.4156017166096717
purpose: []
